version: '3.8'
services:
  mega-ai:
    image: quay.io/qasimtech/mega-ai:v4.0.0
    container_name: mega-ai
    restart: unless-stopped
    working_dir: /root/mega-ai
    volumes:
      - mega_ai_data:/root/mega-ai
      - ./watch.sh:/root/mega-ai/watch.sh
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      BOT_NUMBER: ${BOT_NUMBER}
      REMOVEBG_KEY: ${REMOVEBG_KEY}
      TIME_ZONE: ${TIME_ZONE}
      BOTNAME: ${BOTNAME}
      OWNERS: ${OWNERS}
      MODE: ${MODE}
      PREFIX: ${PREFIX}
    command: sh -c "
      git clone https://github.com/GlobalTechInfo/MEGA-AI /root/mega-ai || true &&
      rm -rf /root/mega-ai/.git &&
      chmod +x /root/mega-ai/watch.sh &&
      cd /root/mega-ai &&
      npm install || yarn install &&
      ./watch.sh"

volumes:
  mega_ai_data:
  
