version: '3.8'

services:
  mega-bot:
    image: quay.io/qasimtech/mega-bot:latest
    container_name: mega-bot
    restart: unless-stopped
    working_dir: /root/mega
    volumes:
      - mega_data:/root/mega
      - ./watch.sh:/root/mega/watch.sh
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: ${MONGODB_URI:-mongodb://localhost:27017}
      BOT_NUMBER: ${BOT_NUMBER:-923204566005}
      REMOVEBG_KEY: ${REMOVEBG_KEY:-none}
      TIME_ZONE: ${TIME_ZONE:-Asia/Karachi}
      BOTNAME: ${BOTNAME:-MEGA-BOT}
      OWNERS: ${OWNERS:-923204566005}
      MODE: ${MODE:-public}
      PREFIX: ${PREFIX:-.}
    command: sh -c "
      git clone https://github.com/GlobalTechInfo/MEGA-AI /root/mega || true &&
      rm -rf /root/mega/.git &&
      chmod +x /root/mega/watch.sh &&
      cd /root/mega &&
      npm install || yarn install &&
      ./watch.sh"

volumes:
  mega_data:
